# Pandas 과제

In [1]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 1) 타이타닉 데이터를 데이터프레임으로 불러오기
### A. 과제게시판 - 타이타닉데이터 다운로드 및 데이터 불러오기

In [27]:
df = pd.read_csv("/content/drive/MyDrive/데이터분석과 머신러닝/타이타닉데이터셋 (1).csv")

## 2) 타이타닉 데이터 프레임에 대해 요약 기능 사용하기

'''
    TODO:: 데이터 프레임 요약 기능 사용해보기
'''

In [28]:
# 데이터 프레임의 구조 요약
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [29]:
# 데이터 프레임의 기술 통계 요약
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

### 타이타닉 데이터 컬럼 설명
- PassangerID : 승객 ID
- Survived : 생존 여부, 0=사망, 1=생존
- Pclass : 티켓의 등급 (1=1st, 2=2nd, 3=3rd)
- Name : 승객의 이름
- Sex : 성별
- Age : 연령
- SibSp : 타이타닉호에 탑승한 형제/배우자의 수
- Parch : 타이타닉호에 탑승한 부모/자녀 수
- Ticket : 티켓 번호
- Fare : 승객 요금
- Cabin : 객실 번호
- Embarked : 탑승 위치

In [30]:
del df['Cabin'] # Cabin 열 전체 삭제
df = df.dropna() # 결측치 (NaN)가 하나라도 있는 행을 제거한 결과를 다시 df에 저장
df = df.reset_index(drop=True)  # 인덱스를 0부터 다시 지정
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...,...
326,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,S
327,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,Q
328,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,S
329,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C
330,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S

## 3) 타이타닉 데이터 프레임 Human_classfi 컬럼 추가하기
- 남자이며, 19세 미만은 [Child_m]으로 설정
- 여자이며, 19세 미만은 [Child_f]으로 설정
- 남자이며, 19세 이상은 [Mr]으로 설정
- 여자이며, 19세 이상은 [Ms]으로 설정

'''
    TODO:: Human_classfi 컬럼 추가 (위 조건에 맞는 값으로 넣을것)
    Hint : loc 함수 사용, 다중 조건 사용
'''

In [32]:
df['Age'].dtype

dtype('float64')

In [50]:
df.loc[(df['Sex'] == 'male') & (df['Age'] < 19), 'Human_classfi']= 'Child_m'
df.loc[(df['Sex'] == 'female') & (df['Age'] < 19), 'Human_classfi'] = 'Child_f'
df.loc[(df['Sex'] == 'male') & (df['Age'] >= 19), 'Human_classfi'] = 'Mr'
df.loc[(df['Sex'] == 'female') & (df['Age'] >= 19), 'Human_classfi'] = 'Ms'

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Human_classfi
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q,Mr
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S,Ms
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q,Mr
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S,Mr
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S,Ms
...,...,...,...,...,...,...,...,...,...,...,...,...
326,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,S,Child_f
327,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,Q,Ms
328,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,S,Ms
329,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C,Ms
330,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S,Mr

## 4) 아래의 데이터 프레임을 타이타닉 데이터 프레임에 조인하기

'''
    TODO:: 타이타닉 데이터 프레임에 위 데이터 프레임을 조인하기
    Hint : 키는 Human_classfi로 설정, merge, join 등 함수 사용하기
'''

In [38]:
data_dict = {
    "Human_classfi" : ['Child_m', 'Child_f', 'Mr', 'Ms'],
    "HC_DES" : ['19세 미만의 남성', '19세 미만의 여성','19세 이상의 남성','19세 이상의 여성']
}

des_df = pd.DataFrame(data_dict)
des_df

  Human_classfi      HC_DES
0       Child_m  19세 미만의 남성
1       Child_f  19세 미만의 여성
2            Mr  19세 이상의 남성
3            Ms  19세 이상의 여성

In [41]:
pd.merge(df, des_df, on='Human_classfi', how='left')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Human_classfi,Human_calssfi,HC_DES
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q,Mr,NaN,19세 이상의 남성
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S,Ms,NaN,19세 이상의 여성
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q,Mr,NaN,19세 이상의 남성
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S,Mr,NaN,19세 이상의 남성
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S,Ms,NaN,19세 이상의 여성
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,S,Child_f,NaN,19세 미만의 여성
327,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,Q,Ms,NaN,19세 이상의 여성
328,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,S,Ms,NaN,19세 이상의 여성
329,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C,Ms,NaN,19세 이상의 여성
330,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S,Mr,NaN,19세 이상의 남성

## 5) Human_classfi 별 생존자 수 확인하기

'''
    TODO:: Human_classfi 별 생존자 수 확인하기
    Hint : 그룹화 할 수 있는 함수를 이용하여 Human_classfi를 기준으로 생존자 수 합산하기
'''

In [55]:
df.groupby('Human_classfi')['Survived'].sum()

Human_classfi
Child_f     25
Child_m      0
Mr           0
Ms         102
Name: Survived, dtype: int64